In [13]:
from pathlib import Path
import geopandas as gpd
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = PROJECT_ROOT / "data"
PROCESSED_BOUNDARIES_DIR = DATA_DIR / "boundaries" / "processed"
BOUNDARIES_DIR = DATA_DIR / "boundaries"
TOC_DIR = BOUNDARIES_DIR / "tocs"
VILLAGES_DIR = BOUNDARIES_DIR / "villages"

toc_gpkg = PROCESSED_BOUNDARIES_DIR / "toc_clean.gpkg"
villages_gpkg = PROCESSED_BOUNDARIES_DIR / "village_clean.gpkg"
toc_csv = TOC_DIR / "tocs_demographics_cleaned.csv"
villages_csv = VILLAGES_DIR / "villages_demographics_cleaned.csv"

toc_gpkg, villages_gpkg, toc_csv, villages_csv

(WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/processed/toc_clean.gpkg'),
 WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/processed/village_clean.gpkg'),
 WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/tocs/tocs_demographics_cleaned.csv'),
 WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/villages/villages_demographics_cleaned.csv'))

In [14]:
toc = gpd.read_file(toc_gpkg)
villages = gpd.read_file(villages_gpkg)
toc_df = pd.read_csv(toc_csv)
villages_df = pd.read_csv(villages_csv)

print("TOC GPKG:", len(toc))
print("TOC CSV:", len(toc_df))
print("Villages GPKG:", len(villages))
print("Villages CSV:", len(villages_df))

TOC GPKG: 11
TOC CSV: 11
Villages GPKG: 15
Villages CSV: 15

In [15]:
print(toc.columns)
print(toc_df.columns)

Index(['OBJECTID', 'APPLICABIL', 'geometry'], dtype='object')
Index(['TOC_ID', 'APPLICABIL', 'income_weighted', 'rent_weighted', 'hh_total',
       'median_income_approx', 'median_rent_approx', 'intersect_acres',
       'ASNQE001', 'ASS8E001', 'ASS8E002', 'ASS8E003', 'ASS9E002', 'ASS9E003',
       'ASORE001', 'ASORE003', 'ASORE004', 'ASORE010', 'ASORE018', 'ASORE019',
       'ASORE021', 'ASORE002', 'pct_drive_alone', 'pct_transit', 'pct_bike',
       'pct_walk', 'pct_wfh', 'pct_auto'],
      dtype='object')

In [16]:
JOIN_FIELD_TOC = "APPLICABIL"
JOIN_FIELD_TOC_DF = "APPLICABIL"

JOIN_FIELD_TOC, JOIN_FIELD_TOC_DF

('APPLICABIL', 'APPLICABIL')

In [17]:
toc_merge = toc.merge(
    toc_df,
    how="left",
    left_on=JOIN_FIELD_TOC,
    right_on=JOIN_FIELD_TOC_DF,
)

print("Rows after join (must match tract count):", len(toc_merge))
toc_merge.head()

Rows after join (must match tract count): 11

,OBJECTID,APPLICABIL,geometry,TOC_ID,income_weighted,rent_weighted,hh_total,median_income_approx,median_rent_approx,intersect_acres,...,ASORE018,ASORE019,ASORE021,ASORE002,pct_drive_alone,pct_transit,pct_bike,pct_walk,pct_wfh,pct_auto
0,1,TOD District - Gateway,"POLYGON ((663431.678 894322.427, 663434.469 89...",0,2.099283e+08,5.097215e+06,4404.074570,47666.824758,1157.386086,2418.944362,...,80.237735,109.625509,449.088289,5197.669073,62.949051,6.885219,1.241587,1.696329,6.949127,80.427979
1,2,TOD District - Eastlake Garfield,"POLYGON ((654751.939 894390.665, 654764.736 89...",1,1.613483e+08,3.709420e+06,3379.818960,47738.728035,1097.520452,1220.462979,...,24.819494,169.119522,612.777992,2880.542278,62.641426,2.418543,0.639859,4.359989,15.797736,74.261881
2,3,TOD District - Midtown,"POLYGON ((654767.886 907514.625, 654767.631 90...",2,5.228343e+08,1.150085e+07,7079.314543,73853.809662,1624.571152,1283.000217,...,18.990820,309.705123,1576.935853,4738.153812,55.627661,6.914095,0.261316,4.261577,21.698811,65.197519
3,4,TOD District - Uptown,"POLYGON ((649448.684 915530.44, 654791.762 915...",3,4.255024e+08,8.094779e+06,5546.764459,76711.815672,1459.369509,1332.064285,...,39.419910,112.935643,1513.787255,4485.287669,66.306648,4.093010,0.605072,1.733495,23.235733,68.846495
4,5,TOD District - Solano,"POLYGON ((646830.036 919545.608, 646829.436 91...",4,2.998474e+08,7.064961e+06,5518.487681,54335.073430,1280.234957,1100.265433,...,24.968847,359.417134,1223.597030,5030.358146,57.961820,5.484560,0.343444,4.943742,16.830438,69.192002

In [18]:
toc_merge_path = TOC_DIR / "toc_demographics.gpkg"
toc_merge.to_file(toc_merge_path, driver="GPKG")

print("Saved TOC+metrics layer to:", toc_merge_path)

Saved TOC+metrics layer to: c:\Users\arjav\DevSource\toc-performance-dashboard\data\boundaries\tocs\toc_demographics.gpkg

In [19]:
print(villages.columns)
print(villages_df.columns)

Index(['OBJECTID', 'NAME', 'geometry'], dtype='object')
Index(['NAME', 'ASNQE001_w', 'ASS8E002_w', 'ASS8E003_w', 'intersect_acres',
       'pop_per_acre', 'hh_per_acre', 'ASS9E002_w', 'ASS9E003_w',
       'median_income_approx', 'median_rent_approx', 'pct_drive_alone',
       'pct_transit', 'pct_bike', 'pct_walk', 'pct_wfh', 'pct_auto'],
      dtype='object')

In [20]:
JOIN_FIELD_VILLAGES = "NAME"
JOIN_FIELD_VILLAGES_DF = "NAME"

JOIN_FIELD_VILLAGES, JOIN_FIELD_VILLAGES_DF

('NAME', 'NAME')

In [21]:
village_merge = villages.merge(
    villages_df,
    how="left",
    left_on=JOIN_FIELD_VILLAGES,
    right_on=JOIN_FIELD_VILLAGES_DF
)

print("Rows after join (must match tract count):", len(village_merge))
village_merge.head()

Rows after join (must match tract count): 15

,OBJECTID,NAME,geometry,ASNQE001_w,ASS8E002_w,ASS8E003_w,intersect_acres,pop_per_acre,hh_per_acre,ASS9E002_w,ASS9E003_w,median_income_approx,median_rent_approx,pct_drive_alone,pct_transit,pct_bike,pct_walk,pct_wfh,pct_auto
0,16,Ahwatukee Foothills,"POLYGON ((683945.25 859952.062, 683930.25 8598...",80121.395673,33008.638620,1921.779283,22832.880975,3.509036,1.445662,23107.487000,9901.151621,116395.759419,2028.861097,65.998273,0.497064,0.378675,1.030677,23.784279,73.094973
1,17,Laveen,"POLYGON ((638589.25 843376, 629247.625 838551....",68987.873610,19775.759721,625.264658,19579.686598,3.523441,1.010014,15500.707650,4275.052071,102147.436370,1774.052390,67.500289,1.577105,0.221852,0.641848,17.759230,78.571462
2,18,South Mountain,"POLYGON ((683945.25 859952.062, 683530.875 860...",125752.337014,41006.060284,2343.525244,25481.856132,4.934976,1.609226,25893.514202,15112.546082,72757.192647,1508.724056,69.346365,1.376917,0.222369,0.904883,15.840799,79.559547
3,19,Estrella,"POLYGON ((607040.694 890232.667, 607046.417 89...",103023.425643,26650.951390,1084.744162,26503.624912,3.887145,1.005559,16828.846503,9822.104887,75184.153423,1580.769165,68.506736,1.983722,0.161181,0.523910,9.572126,85.576993
4,20,Central City,"POLYGON ((669683.439 897001.625, 672160.625 89...",58532.832473,24096.557696,3248.797954,13600.592409,4.303697,1.771729,5997.054184,18099.503513,52293.256403,1266.640455,59.867798,4.629652,1.118289,4.122824,16.984972,71.437084

In [22]:
village_merge_path = VILLAGES_DIR / "village_demographics.gpkg"
village_merge.to_file(village_merge_path, driver="GPKG")

print("Saved village+metrics layer to:", village_merge_path)

Saved village+metrics layer to: c:\Users\arjav\DevSource\toc-performance-dashboard\data\boundaries\villages\village_demographics.gpkg